### ISSUE TITLE
Cannot read properties of undefined (reading 'start')

### ISSUE THREAD

**Issue by zoneblaze** [pixijs/pixi-projection#102]
Hi there, since updating pixi.js to 6.2.x I am getting this error, reverting back to 6.1.x fixes it for me, any ideas?

```
core.js:4507 Uncaught TypeError: Cannot read properties of undefined (reading 'start')
    at BatchSystem.setObjectRenderer (core.js:4507:1)
    at Sprite3d._render (pixi-projection.js:4066:1)
    at Sprite3d.Container.render (display.js:1835:1)
    at Container3d.Container.render (display.js:1838:1)
    at Camera3d.Container.render (display.js:1838:1)
    at Container.render (display.js:2369:1)
    at Container.render (display.js:2369:1)
    at Renderer.render (core.js:10062:1)
    at Application.render (app.js:96:1)
    at TickerListener.emit (ticker.js:100:1)
```

**Comment by ivanpopelyshev** [comment]
Usually that's a double-pixi issue. `rm node_modules -rf` `rm package-lock.json`  `npm i`

pixi projection deps are all v6: https://github.com/pixijs/pixi-projection/blob/4196d66f392e81c62b571af6201fbc0f7db5de15/package.json#L73-L83 , so it shouldnt be a problem

**Comment by zoneblaze** [comment]
That fixed it, thank you for the quick reply!
